CREATE TABLE [lutblHelpText] (
  [helpTextID] AUTOINCREMENT CONSTRAINT [Index_5D5326A4_9457_49C3] UNIQUE  CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [frmName] VARCHAR (255),
  [Title] VARCHAR (255),
  [HelpText] LONGTEXT 
)
