CREATE TABLE [tblDeterminationMemo] (
  [DMid] AUTOINCREMENT CONSTRAINT [Index_7EAF57AC_6409_49AD] UNIQUE  CONSTRAINT [Index_93BA47FB_86F2_4131] UNIQUE  CONSTRAINT [Index_DF23F427_1A8B_4741] UNIQUE  CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [ItemType] VARCHAR (255),
  [DisasterID] VARCHAR (255),
  [ApplicantID] VARCHAR (255),
  [ProjectID] LONG ,
  [Lane Assigned] VARCHAR (255),
  [SiteID] LONG ,
  [Determination Action] VARCHAR (255),
  [Determination Reason] LONGTEXT ,
  [Memo Assigned to] VARCHAR (255),
  [Response Time Requested] LONG ,
  [Date memo complete] DATETIME ,
  [Date Returned from Recipient] DATETIME ,
  [Transmittal letter Prepared by] VARCHAR (255),
  [Date letter complete] DATETIME ,
  [Date PMTFL Concurs] DATETIME ,
  [Date PAGS Concurs] DATETIME ,
  [Date FCO signs letter] DATETIME ,
  [DateTransmitted to Recipient] DATETIME ,
  [Date Trasmitted to Applicant] DATETIME ,
  [Transmittal Method] VARCHAR (255),
  [ReviewFrom] VARCHAR (255),
  [ReviewFromPhase] LONG DEFAULT 0,
  [ReviewFromStep] LONG DEFAULT 0,
  [DMCanceled] BIT DEFAULT No,
  [CreatedBy] VARCHAR (255),
  [Comments] LONGTEXT ,
  [isWithdrawn] BIT DEFAULT No
)
