CREATE TABLE [tblDisaster] (
  [DisasterID] VARCHAR (255) CONSTRAINT [Index_1B0D9D89_0E8A_40E2] UNIQUE  CONSTRAINT [Index_3453F6D7_F397_4AC3] UNIQUE  CONSTRAINT [Index_43C63EA0_F980_464F] UNIQUE  CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [State] VARCHAR (255),
  [Disaster Type] VARCHAR (255),
  [Declaration Date] DATETIME ,
  [Incident Period Start] DATETIME ,
  [Incident Period End] DATETIME ,
  [JFO Start Date] DATETIME ,
  [JFO End Date] DATETIME ,
  [Processing Center Start Date] DATETIME ,
  [Processing Center End Date] DATETIME ,
  [Cost Share] SINGLE ,
  [Limited Period Cost Share] VARCHAR (255),
  [Cost Share Change Timeframe] VARCHAR (255),
  [PA Lead] VARCHAR (255),
  [FCO] VARCHAR (255),
  [Public Assistance] BIT ,
  [Individual Assistance] BIT ,
  [Hazard Mitigation] BIT ,
  [PAAP Debris 30 Days] DATETIME ,
  [PAAP Debris 90 Days] DATETIME ,
  [PAAP Debris 180 Days] DATETIME ,
  [Permanent Work 18 Months] DATETIME ,
  [Permanent Work 48 Months] DATETIME ,
  [Large Project Threshold] CURRENCY ,
  [Mimimum Site Amount] CURRENCY ,
  [JFO Street Address] VARCHAR (255),
  [JFO City, State, Zip] VARCHAR (255),
  [HSIN Address] VARCHAR (255),
  [RFI Response Email Address] VARCHAR (255)
)
