CREATE TABLE [tblSiteInspections] (
  [ID] AUTOINCREMENT CONSTRAINT [Index_3CEDD4DA_5D47_4DE5] UNIQUE  CONSTRAINT [Index_8EADD56C_68D4_4605] UNIQUE  CONSTRAINT [Index_C4D61454_8487_456F] UNIQUE  CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [DisasterID] VARCHAR (255),
  [ApplicantID] VARCHAR (255),
  [ProjectID] LONG ,
  [SiteID] LONG ,
  [FEMA PDC] VARCHAR (255),
  [Assigned Site Inspector] VARCHAR (255),
  [Date Assigned] DATETIME ,
  [Inspection Date -Start] DATETIME ,
  [Inspection Date - Finish] DATETIME ,
  [Subrecipient Participant] VARCHAR (255),
  [Recipient Participant] VARCHAR (255),
  [PDC Participated] BIT ,
  [EHP Participated] BIT ,
  [Mitigation Specialist Participated] BIT ,
  [Insurance Specialist Participated] BIT ,
  [Inpection Notes] LONGTEXT ,
  [Inspection Complete] BIT ,
  [Additional Inspection needed] BIT ,
  [Reason for Additional Inspections] LONGTEXT ,
  [Inpection Report Complete] BIT ,
  [Subrecipient acknowledges recipeipt of SIR] BIT ,
  [Eligibility Concerns] LONGTEXT ,
  [PDC Notified  WO Complete] DATETIME ,
  [SITFL Notified WO Complete] DATETIME ,
  [DDD Entered into EMMIE] VARCHAR (255),
  [Date of meetng with PDC to brief DDD] VARCHAR (255),
  [FEMA PDC Concurs with DDD] BIT ,
  [State PDC Concurs with DDD] BIT ,
  [Subrecipeint Concurs with DDD] BIT ,
  [DIU Attaches DDD in EMMIE] DATETIME ,
  [Lane Assigned] VARCHAR (255),
  [isWithdrawn] BIT DEFAULT No
)
