CREATE TABLE [tblSubRecipientExploratoryCall] (
  [DisasterID] VARCHAR (255),
  [ApplicantID] VARCHAR (255),
  [Eligible] BIT ,
  [Type] VARCHAR (255),
  [Status] VARCHAR (255),
  [Date RPA Received] DATETIME ,
  [RPA Entered into EMMIE] DATETIME ,
  [Determination Entry into EMMIE] DATETIME ,
  [OCC Notes] LONGTEXT ,
  [PAGS Eligibility Determination] VARCHAR (255),
  [Assigned PDC] VARCHAR (255),
  [Exploratory Call Date/Time] DATETIME ,
  [Exploratory Call FEMA Participants] VARCHAR (255),
  [Date Exploratory Call Checklist emailed to Subrecipient] DATETIME ,
  [RSM Agenda sent to Subrecipient] VARCHAR (255),
  [Exploratory Call Notes] VARCHAR (255),
  [EHP Staff Required at RSM] BIT ,
  [Insurance Staff Required at RSM] BIT ,
  [Mitigation Staff Required at RSM] BIT ,
  [Are there any known Environmental or Historic Preservation Issu] BIT ,
  [Can Site Inspections be conducted] BIT ,
  [Is all disaster-related work completed] BIT ,
  [Donated Resources] BIT ,
  [Critical Infrastructure Damaged] BIT ,
  [Describe Damaged Critical Infrastructure] LONGTEXT ,
  [Specialized Staff Required?] BIT ,
  [Types of Specialized Staff] LONGTEXT ,
  [Temporary Space needed] BIT ,
  [Date Exploratory Call Information uploaded to EMMIE] DATETIME ,
  [Recovery Scoping Meeting Date] DATETIME ,
  [Recovery Scoping Meeting Time] DATETIME ,
  [Recovery Scoping Meeting Location] VARCHAR (255),
  [Recipient POC] VARCHAR (255),
  [Recipient POC Contact Number] VARCHAR (255),
  [Subrecipient POC] VARCHAR (255),
  [Subrecipient POC Contact Number] VARCHAR (255),
  [FEMA Participants] LONGTEXT ,
  [Subrecipient Emergency Manager] BIT ,
  [Subrecipient Insurance Risk Manager] BIT ,
  [Subrecipient Environmental/Historic Specialist] BIT ,
  [Subrecipient Public Works Staff] BIT ,
  [Subrecipient Finance Representative] BIT ,
  [Subrecipient Engineering Representative] BIT ,
  [Subrecipient Police/Fire Representatives] BIT ,
  [A Debris Removal # of Small Projects] LONG ,
  [B Protective Measures # of Small Projects] LONG ,
  [C Roads & Bridges # of Small Projects] LONG ,
  [D Water Control Facilities # of Small Projects] LONG ,
  [E Public Buildings # of Small Projects] LONG ,
  [F Public Utilities # of Small Projects] LONG ,
  [G Recreational or Other # of Small Projects] LONG ,
  [A Debris Removal $ Small Projects] LONG ,
  [B Protective Measures $ Small Projects] LONG ,
  [C Roads & Bridges $ Small Projects] LONG ,
  [D Water Control Facilities $ Small Projects] LONG ,
  [E Public Buildings $ Small Projects] LONG ,
  [F Public Utilities $ Small Projects] LONG ,
  [G Recreational or Other $ of Small Projects] LONG ,
  [A Debris Removal # of Large Projects] LONG ,
  [B Protective Measures # of Large Projects] LONG ,
  [C Roads & Bridges # of Large Projects] LONG ,
  [D Water Control Facilities # of Large Projects] LONG ,
  [E Public Buildings # of Large Projects] LONG ,
  [F Public Utilities # of Large Projects] LONG ,
  [G Recreational or Other # of Large Projects] LONG ,
  [A Debris Removal $ of Large Projects] LONG ,
  [B Protective Measures $ of Large Projects] LONG ,
  [C Roads & Bridges $ of Large Projects] LONG ,
  [D Water Control Facilities $ of Large Projects] LONG ,
  [E Public Buildings $ of Large Projects] LONG ,
  [F Public Utilities $ of Large Projects] LONG ,
  [G Recreational or Other $ of Large Projects] LONG ,
  [A Debris Removal Has the work begun] BIT ,
  [B Protective Measures Has the work begun] BIT ,
  [C Roads & Bridges Has the work begun] BIT ,
  [D Water Control Facilities Has the work begun] BIT ,
  [E Public Buildings Has the work begun] BIT ,
  [F Public Utilities Has the work begun] BIT ,
  [G Recreational or Other Has the work begun] BIT ,
  [A Debris Removal Is the work complete] BIT ,
  [B Protective Measures Is the work complete] BIT ,
  [C Roads & Bridges Is the work complete] BIT ,
  [D Water Control Facilities Is the work complete] BIT ,
  [E Public Buildings Is the work complete] BIT ,
  [F Public Utilities Is the work comlete] BIT ,
  [G Recreational or Other Is the work complete] BIT ,
  [Date Exploratory Call Information Entered into EMMIE] DATETIME ,
  [EMMIE Entry Assigned To] VARCHAR (255),
  [A # of Sites] LONG ,
  [B # of Sites] LONG ,
  [C # of Sites] LONG ,
  [D # of Sites] LONG ,
  [E # of Sites] LONG ,
  [F # of Sites] LONG ,
  [G # of Sites] LONG ,
  [A % of Work Complete] DOUBLE ,
  [B % of Work Complete] DOUBLE ,
  [C % of Work Complete] DOUBLE ,
  [D % of Work Complete] DOUBLE ,
  [E % of Work Complete] DOUBLE ,
  [F % of Work Complete] DOUBLE ,
  [G % of Work Complete] DOUBLE ,
   CONSTRAINT [PrimaryKey] PRIMARY KEY ([DisasterID], [ApplicantID])
)
