CREATE TABLE [tblSites] (
  [DisasterID] VARCHAR (255),
  [ApplicantID] VARCHAR (255),
  [ProjectID] LONG DEFAULT 0,
  [SiteID] LONG ,
  [Category] VARCHAR (255),
  [Name of Site/Facility] VARCHAR (255),
  [E911 Street Address or Closest Intersection] LONGTEXT ,
  [Latitude] DOUBLE ,
  [Longitude] DOUBLE ,
  [Describe Damage] LONGTEXT ,
  [Cause of Damage  (wind, flood, etc)] VARCHAR (255),
  [Requires Site Inspection] VARCHAR (255),
  [Approximate Cost] CURRENCY ,
  [% Work Complete] DOUBLE ,
  [Labor Type] VARCHAR (255),
  [EHP Issues? (H, E, B)] VARCHAR (255),
  [Facility insured?] VARCHAR (255),
  [Has Recieved PA grant in prior Stafford Act Disasters?] VARCHAR (255),
  [Is there a potential mitigation opportunity?] VARCHAR (255),
  [Subrecipient priority (Low, Med, High)] VARCHAR (255),
  [Function] VARCHAR (255),
  [Critical Facility] VARCHAR (255),
  [Damage Level] VARCHAR (255),
  [Documentation Notes] LONGTEXT ,
  [Potential OFA Responsibility] VARCHAR (255),
  [Specialized Technical Skill needed] BIT ,
  [Describe Skill] LONGTEXT ,
  [Work 100% Complete] VARCHAR (255),
  [If no, % complete] LONG ,
  [Date Expected to be 100% Complete] DATETIME ,
  [Work Order Recieved by SITFL] BIT ,
  [SITFL Reviews Work Order] DATETIME ,
  [Assign Site Inspection] BIT ,
  [SITFL Contacts PDC to schedule] DATETIME ,
  [Assigned Site Inspector] VARCHAR (255),
  [Date Assigned] DATETIME ,
  [Subrecipient POC] VARCHAR (255),
  [Recipient POC] VARCHAR (255),
  [Site Inspection Location] LONGTEXT ,
  [DVS -Site Inspection Required] VARCHAR (255),
  [Legal Responsiblity] VARCHAR (255),
  [In Declared Area] VARCHAR (255),
  [Caused by the Event] VARCHAR (255),
  [Prepare Site Inspection Work Order] VARCHAR (255),
  [Work Complete] VARCHAR (255),
  [Site Requires DDD Validation] BIT ,
  [Draft DDD] LONGTEXT ,
  [Site Validation Returned] DATETIME ,
  [Site information Complete] BIT ,
  [Documentation Reviewed] BIT ,
  [Documentation Complete] BIT ,
  [RFI Required] BIT ,
  [Assignment Received by Site Inspector] DATETIME ,
  [Work Order Review Complete] DATETIME ,
  [EHP Specialist  requested for Site Inspection] BIT ,
  [Assigned EHP Specialists] VARCHAR (255),
  [EHP Site Inspection Report Required] BIT ,
  [Mitgation Specialists requested for Staff Meeting] BIT ,
  [Assigned Mitigation Specialist] VARCHAR (255),
  [Mitigation Site Inspection Report Requested] BIT ,
  [Insurance Specialist requested for Site Inspection] BIT ,
  [Assigned Insurance Specialist] VARCHAR (255),
  [Insurance Inspection Report Required] BIT ,
  [Scheduled Date of Site Inspection] DATETIME ,
  [Projected time to complete site inspoection] VARCHAR (255),
  [Date of Site Inspection] DATETIME ,
  [SI has Subrecipient Agent sign draft site DDD] DATETIME ,
  [Date SI Notifies PDC the SI is complete] DATETIME ,
  [Date of SI-PDC Briefing] DATETIME ,
  [PDC Concurs] VARCHAR (255),
  [PDC Briefs Recipient-Subrecipient] DATETIME ,
  [Subrecipient and Recipient Concur] VARCHAR (255),
  [SI Enters DDD Into EMMIE] DATETIME ,
  [Include in Project] BIT ,
  [Scope of Work Developed by] VARCHAR (255),
  [Cost Estimate Developed by] VARCHAR (255),
  [Date Subrecipient provides Scope of Work] DATETIME ,
  [Date Subrecipient provides Cost Estimate] DATETIME ,
  [Assigned Costing Specialists] VARCHAR (255),
  [COS Completes PW Template] DATETIME ,
  [COS Imputs Site SOW and Cost into Update Application] DATETIME ,
  [Scope Validation Comments] LONGTEXT ,
  [Cost Estimate Validation Comments] LONGTEXT ,
  [Site Complete] BIT ,
  [Inspection Notes] LONGTEXT ,
  [Inspection Report Complete] BIT DEFAULT No,
  [Eligibility Concerns] LONGTEXT ,
  [Scheduled Time of Site Inspection] DATETIME ,
  [DimensionsKnown] VARCHAR (255),
  [DimensionsFrom] VARCHAR (255),
  [PartOfVerificationSample] VARCHAR (255),
  [KnownDimensionsInEMMIE] VARCHAR (255),
  [UpdatedCost] CURRENCY DEFAULT 0,
  [isWithdrawn] BIT DEFAULT No,
   CONSTRAINT [PrimaryKey] PRIMARY KEY ([DisasterID], [ApplicantID], [ProjectID], [SiteID])
)
