CREATE TABLE [importRpa] (
  [Disaster Number] VARCHAR (255),
  [Applicant ID] VARCHAR (255),
  [Applicant Name] VARCHAR (255),
  [Applicant Eligibility] VARCHAR (255),
  [Applicant Type] VARCHAR (255),
  [RPA Review Status] VARCHAR (255),
  [Application Closed Status] VARCHAR (255),
  [County] VARCHAR (255),
  [RPA Received Date] VARCHAR (255),
  [PNP Status] VARCHAR (255),
  [RPA Entry Date] VARCHAR (255),
  [RPA Approved Date] VARCHAR (255),
  [Public Assistance Coordinator] VARCHAR (255),
  [Contact Name] VARCHAR (255),
  [Contact Title] VARCHAR (255),
  [Contact Phone Number] VARCHAR (255),
  [Contact Email] VARCHAR (255),
  [Alternate Contact Name] VARCHAR (255),
  [Alternate Contact Title] VARCHAR (255),
  [Alternate Business Number] VARCHAR (255),
  [Alternate Contact Email] VARCHAR (255),
  [Kickoff Meeting Date] VARCHAR (255),
  [Kickoff Meeting Location] VARCHAR (255),
  [Kickoff Meeting Status] VARCHAR (255),
  [Exit Briefing Date] VARCHAR (255),
  [Actual Projects] VARCHAR (255)
)
