dbMemo "SQL" ="SELECT tblRFIRequestedInformation.RfiItemID, tblRFIRequestedInformation.*, tblRF"
    "IItemType.FurthestProgression, tblSites.[Name of Site/Facility]\015\012FROM (tbl"
    "RFIRequestedInformation LEFT JOIN tblRFIItemType ON tblRFIRequestedInformation.I"
    "temType = tblRFIItemType.Item) LEFT JOIN tblSites ON (tblRFIRequestedInformation"
    ".ProjectID = tblSites.ProjectID) AND (tblRFIRequestedInformation.SiteID = tblSit"
    "es.SiteID) AND (tblRFIRequestedInformation.DisasterID = tblSites.DisasterID) AND"
    " (tblRFIRequestedInformation.ApplicantID = tblSites.ApplicantID)\015\012ORDER BY"
    " tblRFIRequestedInformation.RfiItemID;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
